version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: [MYSQL_ROOT_PASSWORD]
            MYSQL_DATABASE: [MYSQL_DATABASE_NAME]
            MYSQL_USER: [MYSQL_USERNAME]
            MYSQL_PASSWORD: [MYSQL_PASSWORD]
        networks:
            - bookstore_net
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - 80:80
        networks:
            - bookstore_net

networks:
    bookstore_net:
        driver: bridge
