version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: Abcd1234
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: aziz
            MYSQL_PASSWORD: Aziz_123
        networks:
            - bookstore_net
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - 80:80
        networks:
            - bookstore_net

networks:
    bookstore_net:
        driver: bridge
